k8s_yaml('ssh-keys-dev.yaml')
k8s_yaml('session.yaml')
k8s_yaml('master.yaml')
k8s_yaml('postgres.yaml')

 # N:N format due to bug in tilt. The 4001 port goes to the 2200 one otherwise.
k8s_resource('session', port_forwards=['2200:2200', '4001:4001'])
k8s_resource('master', port_forwards=[4000, 4080])
k8s_resource('postgres', port_forwards=[5432])

docker_build('tmate/tmate-ssh-server', '../../tmate-ssh-server',
             dockerfile='../../tmate-ssh-server/Dockerfile.dev',
             live_update=[fall_back_on(['../../tmate-ssh-server/Makefile.am']),
                          sync('../../tmate-ssh-server', '/src/tmate-ssh-server'),
                          run('make -j "$(nproc)"'),
                          restart_container()]
)

docker_build('tmate/tmate-proxy', '../../tmate-proxy',
             dockerfile='../../tmate-proxy/Dockerfile.dev',
             live_update=[fall_back_on(['../../tmate-master/config',
                                        '../../tmate-proxy/mix.exs',
                                        '../../tmate-proxy/mix.lock']),
                          sync('../../tmate-proxy', '/src/tmate-proxy'),
                          run('echo recompile >> console')]
)

docker_build('tmate/tmate-master', '../../tmate-master',
             dockerfile='../../tmate-master/Dockerfile.dev',
             live_update=[fall_back_on(['../../tmate-master/config',
                                        '../../tmate-master/mix.exs',
                                        '../../tmate-master/mix.lock']),
                          sync('../../tmate-master', '/src/tmate-master'),
                          run('echo recompile >> console')]
)
